# MIT 6.036 Fall 2021: Homework 6
## Neural Networks

In [4]:
import numpy as np

# **Softmax Implementation**

You may find it helpful to implement a softmax function to use for solving some of the problems, or work it out by hand. You can then call your softmax on z, which you can also find computationally or by hand. 

In [7]:
# Implement Softmax
def SM(z):
  return np.exp(z)/np.sum(np.exp(z))

# **Problem 1**

You can work these out by hand or computationally. 

**Problem 1.2.1**



In [10]:
z = np.array([[-1, 0, 1]]).T
print(SM(z))

[[0.09003057]
 [0.24472847]
 [0.66524096]]


**Problem 1.2.3-1.2.6**

In [39]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T

# HINT: 
z = w.T@x
a = SM(z)
g = np.sum(y*np.log(a))
dw = x@(a - y).T
w = w - 0.5 * dw
print(w)

print(SM(w.T@x))

[[ 0.87763576 -0.83262048 -2.04501529]
 [-1.12236424  2.16737952  0.95498471]]
[[0.15918761]
 [0.77245284]
 [0.06835955]]


# **Problem 2**

**2.1 ReLU Activation**

You may choose to draft your implementation here. We recommend looking at the ReLU plot at the top of the homework page for better understanding.

In [47]:
def ReLU(z):
  return np.where(z>0, z, 0)

def dReLU_dz(z):
    '''
    z is a column vector
    You should return a column vector
    '''
    return np.where(z>0, 1, 0)


In [41]:
# Test case: you can test your code on the numpy array np.array([[1], [-2], [10]])
# Expected result is array([[1],[0],[1]])

dReLU_dz(np.array([[1], [-2], [10]]))

array([[1],
       [0],
       [1]])

In [54]:
# Empty code cell to continue getting your answers for Problem 2 computationally...
W1_mat = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
W1_offset = np.array([[-1], [-1], [-1], [-1]])
W2_mat = np.array([[1, -1], [1, -1], [1, -1], [1, -1]])
W2_offset = np.array([[0], [2]])

x = [[-3], [0.5]]

# Your code here
z1 = W1_mat.T@x + W1_offset
a1 = ReLU(z1)
print(a1)
z2 = W2_mat.T@a1 + W2_offset
# print(z2)
a2 = SM(z2)
# print(a2)

[[0.]
 [0.]
 [2.]
 [0.]]
